[package]
name = "jsonl_tools"
version = "0.1.0"
edition = "2024"

[dependencies]
num-format = "0.4.4"
serde = "1.0.219"
serde_json = "1.0.141"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[lib]
name = "jsonl_tools"
